apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebay-app
spec:
  selector:
    matchLabels:
      environment: dev
      app: ebay
  replicas: 1
  template:
    metadata:
      labels:
        environment: dev
        app: ebay
    spec:
      volumes:
      - name: volume
        hostPath:
          path: /var/lib/docker/volume/
      containers:
      - name: container1-nginx
        image: nginx:latest
        volumeMounts:
        - name: volume
          mountPath: "/var/nginx-data"

      - name: container2-tomcat
        image: tomcat:latest
        volumeMounts:
        - name: volume
          mountPath: "/mnt/tomcat-data"
